version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: apigateway
    restart: always
    environment:
      POSTGRES_DB: apigateway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d apigateway"]
      interval: 10s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
